---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration

k3s_control_node: true

k3s_server:
  node-ip: "{{ ansible_host }}"
  write-kubeconfig-mode: "644"
  docker: false
  flannel-backend: "none"
  disable:
    - flannel                         # replaced with Tigera Operator Helm Chart
    - metrics-server                  # installed with Flux
    - servicelb                       # replaced with MetalLB Helm Chart
    - traefik                         # replaced with ingress-nginx Helm Chart

  disable-network-policy: true
  disable-cloud-controller: true
  disable-kube-proxy: false
  disable-helm-controller: true

  cluster-cidr: "{{ k3s_cluster_cidr }}"
  service-cidr: "{{ k3s_service_cidr }}"

  kubelet-arg:
    - "image-gc-high-threshold=64"
    - "image-gc-low-threshold=55"
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"
  kube-proxy-arg:
    - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"
  kube-apiserver-arg:
    - "bind-address=0.0.0.0"

  node-taint:
    - "node-role.kubernetes.io/control-plane:NoSchedule"
