---
docker_users: ["{{ ansible_user }}"]
apt_install_packages:
  - vim
  - curl
  - wget
  - nano
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - net-tools
  - htop
  - unzip
  - arptables
  - arping
  - strace
  - software-properties-common
  - unzip
  - dnsutils
  - iputils-ping
  - python3-docker
