---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

dotenv: [".envrc"]

env:
  ANSIBLE_CONFIG: "{{.ROOT_DIR}}/ansible.cfg"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"

includes:
  sops: ./.taskfiles/Sops/Taskfile.yaml
  pre-commit: ./.taskfiles/Precommit/Taskfile.yaml
  kubernetes:
    aliases: ["k8s"]
    taskfile: ./.taskfiles/Kubernetes/Taskfile.yaml
  nas: ./.taskfiles/NAS/Taskfile.yaml

tasks:
  ansible-init:
    desc: Install/Upgrade Ansible galaxy dependencies
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - ansible-galaxy collection install -r requirements.yaml --collections-path ~/.ansible/collections --force
      - ansible-galaxy install -r requirements.yaml --roles-path ~/.ansible/roles --force
  default:
    silent: true
    cmds:
      - task -l
