kind: Secret
ansible_user: ENC[AES256_GCM,data:onXHJORkHIw=,iv:4gPrT1pqkf2Xmqp//IhlN8e3UbUCEN8RUx/JrYf6OZ4=,tag:Fw+fHvjFwLo8P8DvmlZ/Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqydytfsqv3g789ud2jjhrflk445wcadnz0fccrf82zhwfwcgd4q404rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN2NMZmI5ZE5aVUxxKzZq
            di96ZEZ4MzA0T2szd2RPM3JBV3k4TGt2RHlVCnJXNmtMK3pCaGxwdmF0M0w2aTlW
            L25pc0FyTWZHREM5b093YjU1TE5QckUKLS0tIEdML0FNcmx1TUVsMGRTYWlHeGQ5
            YWRYVkkxMGdWSXpzOE1iZ3p4M2Q0RG8Kq6aIaexdrZIIA+TvHN9iEZ4VUX/XWIy9
            Ns6JaVHe5N2esc2ZqwdNcJy9WVjxM7G0DfqW0lnyo1Th5wT8SFRUeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-20T22:08:10Z"
    mac: ENC[AES256_GCM,data:UcxLaX350h5WKizdrhQm1jCHGgn05oVwpVJlQ+5VchDHB/jLyOUYUbCHgfZ8ZliRRyax8HDW9I8iIaNXXhyzZVBUUQMx5lV4HXO2/TShZh55RKz2OKrPzvxbC9p0fO4keLYsG3851sAotuEthVhDGH6jlsYKsbExi3AK9EWvQ0g=,iv:SQM3I17bWAjtI1alF/TuXiZn+5lY5O8ATBdn0JfyzIw=,tag:G4acpcWOGeuhOYP8+J692g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.9.0
