kind: Secret
ansible_user: ENC[AES256_GCM,data:NItDUL3cFco=,iv:lkiKXZfCaq7vyATm/mFOPrfchtTm5ye9aNIzIeWlvR4=,tag:SUWvNyZ9TA4pt7wscUX2aA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zqydytfsqv3g789ud2jjhrflk445wcadnz0fccrf82zhwfwcgd4q404rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYVlFWlhJODBRbVZmWW5t
            NzhxcnZpeEM5VGNpMFVNQlNYS3JXQ0RqTmxFClNYU0dXS3h0YTVzRHZ0RitCTVFY
            TXdDTEU1a3BvSlpFQSs2T1hYRGZHRncKLS0tIGE5eEM2bzArayt3d3czUjROM2w1
            RVRHQmVldE5MNDV0NGlOR2tjbTRIMGcK+48UAjGMzxeqF2fl2FVaUWsxLvWW43g0
            MmmlWiQ76vmJIIsZVGiQf7YH2I2nV02qDlH+o2QmLXZEQNPAJVSI6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-20T22:08:06Z"
    mac: ENC[AES256_GCM,data:/W7MXvJZDgly2/wZxb0beAYZZfho9OJ9vKW1BDqXySmFPN2k9dMgNXPFjHo7q6EZAO21OPnRwJvmjQiAzIHUtv62Abd6tYWD7V3kmzqxZK/YL3wZ6TCX25pVF2daLk90C9C7YcXUbANjAl+aTLe6ijsY6nw3nhILMgopzG7CHHE=,iv:nrLvR8E8TftQkJGlCBu+FPYeaSjGeu5JHp2bS56Zx5M=,tag:Z7ZBpNzrrdIitmMScrp6rA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.9.0
