all:
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
  children:
    kubernetes:
      children:
        controller:
          hosts:
            rift:
              ansible_host: 192.168.1.6
        worker:
          hosts:
            quasar:
              ansible_host: 192.168.1.8
    dnsserver:
      hosts:
        horizon:
          ansible_host: 192.168.1.57
    storage:
      hosts:
        rift: