kubernetes:
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
  children:
    master:
        hosts:
          quasar:
            ansible_host: 192.168.1.102
    worker:
      hosts:
        titan:
          ansible_host: 192.168.1.101
        rift:
          ansible_host: 192.168.1.102
    dnsserver:
      hosts:
        apex:
          ansible_host: 192.168.1.100
    storage:
      hosts:
        titan:
        rift:
