---
- name: Remove /etc/resolv.conf if it exists (file or symlink)
  file:
    path: /etc/resolv.conf
    state: absent

- name: Copy resolv.conf template to /etc/resolv.conf
  template:
    src: 'resolv.conf.j2'
    dest: '/etc/resolv.conf'
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload
