---
- name: System Packages | Upgrade all system packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success

- name: System Packages | Install apt packages list
  ansible.builtin.apt:
    name: "{{ apt_install_packages }}"
    state: present
    update_cache: true
    force_apt_get: yes

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: yes
    purge: true
