---
- name: User Configuration | Add user to sudoers
  ansible.builtin.copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ ansible_user }}_nopasswd"
    mode: "0440"


- name: User Configuration | Silence login
  ansible.builtin.file:
    dest: "{{ '/home/' + ansible_user if ansible_user != 'root' else '/root' }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    modification_time: preserve
    access_time: preserve
