---
k3s_release_version: "v1.30.3+k3s1"
k3s_install_hard_links: true
k3s_etcd_datastore: true
k3s_become: true
k3s_debug: false
k3s_registration_address: "192.168.1.55"
k3s_cluster_cidr: "10.42.0.0/16"
k3s_service_cidr: "10.43.0.0/16"
k3s_server_manifests_templates:
  - custom-cilium-helmchart.yaml.j2
  - custom-coredns-helmchart.yaml.j2
  - custom-kube-vip-daemonset.yaml.j2
  - custom-kube-vip-rbac.yaml.j2
