---
- name: Install dnsserver components
  hosts: dnsserver
  any_errors_fatal: true
  become: false
  gather_facts: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - name: Install Docker, Docker compose (as plugin)
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Install pihole
      ansible.builtin.include_tasks: tasks/pihole.yaml
