---
- name: Install dnsserver components
  hosts: dnsserver
  any_errors_fatal: true
  become: false
  gather_facts: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  roles:
    - name: Install Docker
      role: geerlingguy.docker
      become: true

  tasks:
    - name: Install pihole
      ansible.builtin.include_tasks: tasks/pihole.yaml
