---
- name: Prepare Ubuntu server OS
  hosts: dnsserver
  any_errors_fatal: true
  become: true
  gather_facts: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - name: Prepare Ubuntu server OS
      ansible.builtin.include_role:
        name: os

    - name: Install Docker, Docker compose (as plugin)
      ansible.builtin.include_role:
        name: geerlingguy.docker

  post_tasks:
    - name: Rebooting...
      ansible.builtin.reboot:
        msg: Rebooting hosts
        reboot_timeout: 3600
