---
- name: Reboot all kubernetes nodes
  hosts: all
  become: true
  any_errors_fatal: false
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Rebooting all nodes
      ansible.builtin.reboot:
        msg: Rebooting hosts
        reboot_timeout: 3600
