---
- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Reboot
  ansible.builtin.reboot:
    msg: Rebooting hosts
    reboot_timeout: 3600

- name: Rebuild locales database
  command: "{{ item }}"
  with_items:
    - dpkg-reconfigure locales -f noninteractive
    - /usr/sbin/locale-gen
