---
- name: K3s Cluster Nuke
  hosts:
    - kubernetes
  any_errors_fatal: true
  become: true
  gather_facts: true

  vars_prompt:
    - name: nuke
      prompt: |-
        /!\  Are you sure you want to nuke this k3s cluster?          /!\
        /!\    1. Ensure you have backed up all important data / DBs  /!\
        /!\    2. This will delete all data and cluster state!!!      /!\
        Type CONFIRM to proceed
      default: "n"
      private: false

  pre_tasks:
    - name: Check for confirmation
      ansible.builtin.fail:
        msg: Aborted nuking the cluster
      when: nuke != 'CONFIRM'

    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5

  tasks:
    - name: Stop scheduling pods
      ignore_errors: true
      block:
        - name: Cordon
          kubernetes.core.k8s_drain:
            name: "{{ inventory_hostname }}"
            kubeconfig: /etc/rancher/k3s/k3s.yaml
            state: cordon  # unschedulable
          delegate_to: "{{ groups['controller'][0] }}"

    - name: Stop k3s
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: uninstalled

    - name: Networking | Delete CNI directory
      ansible.builtin.file:
        path: /etc/cni/net.d
        state: absent

    - name: Networking | Flush iptables
      ansible.builtin.iptables:
        table: "{{ item }}"
        flush: true
      loop: ["filter", "nat", "mangle", "raw"]

    - name: Networking | Flush ip6tables
      ansible.builtin.iptables:
        table: "{{ item }}"
        flush: true
        ip_version: ipv6
      loop: ["filter", "nat", "mangle", "raw"]

    - name: Ensure hard links are removed
      when:
        - k3s_install_hard_links
        - not ansible_check_mode
      ansible.builtin.file:
        path: "{{ k3s_install_dir }}/{{ item }}"
        state: absent
      loop: ["kubectl", "crictl", "ctr"]


    - name: Remove longhorn storage path
      ansible.builtin.file:
        path: "/var/lib/longhorn"
        state: absent

    - name: Remove openebs storage path
      ansible.builtin.file:
        path: "/var/openebs/local"
        state: absent


    - name: Stale Containers
      ansible.builtin.include_tasks: tasks/stale_containers.yaml
      vars:
        stale_containers_state: disabled

    - name: Reboot
      ansible.builtin.reboot:
        msg: Rebooting nodes
        reboot_timeout: 3600
