---
- name: Prepare Ubuntu server OS
  hosts: all
  any_errors_fatal: true
  become: true
  gather_facts: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  tasks:
    - name: Prepare Ubuntu server OS
      ansible.builtin.include_role:
        name: os
