---
## This plays will just gather the facts of dnsserver host
- hosts: dnsserver
  gather_subset:
    - all_ipv4_addresses

- name: Prepare Ubuntu server OS
  hosts: kubernetes
  any_errors_fatal: true
  become: true
  gather_facts: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  roles:
    - name: Prepare Ubuntu server OS
      role: os


  post_tasks:
    - name: Rebooting...
      ansible.builtin.reboot:
        msg: Rebooting hosts
        reboot_timeout: 3600
