---
apt_install_packages:
  - vim
  - curl
  - wget
  - nano
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - net-tools
  - gdisk
  - fdisk
  - libusb-dev
  - htop
  - unzip
  - arptables
  - strace
  - arping
  - lvm2
  - nfs-common
  - open-iscsi
  - software-properties-common
  - unzip
  - dnsutils
  - iputils-ping
  - python3-kubernetes
  - python3-yaml
  - rsync

apt_remove_packages:
  - ufw
  - unattended-upgrades
  - apparmor

timezone: "Europe/Paris"
ntp_servers:
  primary:
    - "time.cloudflare.com"
  fallback:
    - "0.us.pool.ntp.org"
    - "1.us.pool.ntp.org"
    - "2.us.pool.ntp.org"

k3s_release_version: "v1.30.3+k3s1"
k3s_install_hard_links: true
k3s_etcd_datastore: true
k3s_become: true
k3s_debug: false
k3s_registration_address: "192.168.1.103"
k3s_cluster_cidr: "10.42.0.0/16"
k3s_service_cidr: "10.43.0.0/16"
k3s_server_manifests_templates:
  - custom-cilium-helmchart.yaml.j2
  - custom-coredns-helmchart.yaml.j2
  - custom-kube-vip-daemonset.yaml.j2
  - custom-kube-vip-rbac.yaml.j2
