---
pool_name: "oasis"
datasets:
  - name: "oasis/Apps"
  - name: "oasis/Apps/Longhorn"
  - name: "oasis/Apps/Minio"
  - name: "oasis/Media"
  - name: "oasis/Media/Movies"
  - name: "oasis/Media/TvShows"
  - name: "oasis/Media/Music"

nodes_cidr: "192.168.1.0/24"
uid: 442
gid: 442

nfs_options: "no_subtree_check,all_squash,anonuid={{uid}},anongid={{gid}},rw=@{{nodes_cidr}}"

storage_required_packages_list:
  - zfs-zed
  - zfsutils-linux
  - nfs-kernel-server
  - nfs-common
  - open-iscsi
  - smartmontools
  - nvme-cli
  - lvm2
  - ffmpeg
  - gdisk
  - fdisk
  - libusb-dev
