---
version: "3"

tasks:

  kubeconfig:
    desc: Download kubeconfig
    cmds:
      - ansible-playbook  -i {{.ANSIBLE_INVENTORY_DIR}}/hosts.yaml {{.ANSIBLE_PLAYBOOK_DIR}}/kubernetes/kubeconfig.yaml
